#!/bin/sh
## A script for running msg-server in booting time.

dlogutil -v threadtime -f /var/log/msgfw.log -r 1000 -n 10 MSG_FW &

if [ ! -e /opt/etc/.hib_capturing ]; then
/usr/bin/msg-server &
fi

